### ISSUE TITLE
Postgresql Mappings

### ISSUE THREAD

**Issue by tobalsgithub** [RuntimeTools/appmetrics-elk#6]
Now that postgresql has been added to the master branch of the appmetrics repo, can we consider adding a mapping for postgresql to this repo? I'm happy to do it. Seems like updating the docs and adding a mappings file in the mappings directory would be all that's required.

**Comment by seabaylea** [comment]
I'm working on uplifting appmetrics-elk to the appmetrics-1.0.4 level, which will include postgresql, mqtt, mylight, redis, etc. The aim is to release both as close together as possible - either same day or just a day or two later.

That should all be happening very soon now ;)

**Comment by tobalsgithub** [comment]
Sweet! Let me know if you need any help.

**Comment by seabaylea** [comment]
Closing based on PR #11
