### ISSUE TITLE
appmetrics support kibana new versions

### ISSUE THREAD

**Issue by dfaropennetwork** [RuntimeTools/appmetrics-elk#8]
it's posible to install on kibana versions 4.2 etc...??

**Comment by seabaylea** [comment]
I've started to take a look at this. There's no issues with support for Kibana 4.2, 4.3 etc in itself, but there are challenges in the fact that later versions of Kibana require you to be using Elasticsearch 2.x.

Elasticsearch 2.x introduced a number of breaking changes with mapping files:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html

We're affected by at least three of those. I've got prototypes that fix two so far (dots in field names, and the use of `compress` has been removed). I'm still working on the third (conflicting mappings for timestamps).

**Comment by seabaylea** [comment]
Closing based on PR #19
